export const products = [
  {
    id: 1,
    category: "corte",
    name: "Sierra circular eléctrica Bosch Professional GKS 150 184mm 1500W azul 220V",
    image1: "https://i.imgur.com/S9kQ0XZ.png",
    image2: "https://i.imgur.com/I2OkLWu.png",
    image3: "https://i.imgur.com/4Iw7V6D.png",
    description:
      "La sierra Bosch GKS 150 posee un diseño compacto que proporciona una alta potencia con poco peso. Es ergonómica y resistente, con una asa robusta que proporciona mayor estabilidad en el corte. Diámetro del disco; disco de 184mm. Posibilita cortes definidos y prolijos, difíciles de alcanzar de manera manual.",
    price: 26900,
    stock: 100,
    initial: 1,
    manufactured: "Bosch",
    model: "GKS 150",
    voltage: 220,
    weight: "3,7",
  },
  {
    id: 2,
    category: "corte",
    name: "Amoladora angular Stanley STGS9115 de 50 Hz amarilla y negra 900 W 220 V + accesorio",
    image1: "https://i.imgur.com/wB8KVi3.png",
    image2: "https://i.imgur.com/6cso5Hw.png",
    image3: "https://i.imgur.com/fAChJPl.png",
    description:
      "La amoladora Stanley es una herramienta versátil, que permite realizar diferentes trabajos con una terminación profesional. Por eso, es una excelente opción sumarla a tu taller o caja de herramientas.      Stanley es una marca con gran trayectoria y reconocimiento mundial. Fabrica herramientas para que trabajes mejor, de manera más eficaz y rápida. Explotá tu potencial con sus productos y alcanzá óptimos resultados. Equipá tu casa o taller y ¡hacelo vos mismo! Esta amoladora angular es perfecta para realizar distintos trabajos de amolado, cepillado y pulido. A su vez, se destaca por ser un elemento indispensable para cortar, desbastar y lijar diversos materiales derivados del metal. Segura y fácil de maniobrar. A la hora de trabajar con herramientas es importante que tu seguridad esté garantizada. Con el botón de bloqueo de disco que trae incorporado reducís al máximo el riesgo cuando trabajás con discos de corte.",
    price: 14249,
    stock: 50,
    initial: 1,
    manufactured: "Stanley",
    model: "STGS9115",
    voltage: 220,
    weight: "1,9",
  },
  {
    id: 3,
    category: "corte",
    name: "Sierra Sensitiva Dewalt D28730 2300w",
    image1: "https://i.imgur.com/S43kpal.png",
    image2: "https://i.imgur.com/1XKgS2i.png",
    image3: "https://i.imgur.com/Vf4o9jS.png",
    description:
      " Características:- Potente motor de 2300w - Diseñado para las aplicaciones más duras.- Diseño Ergonómico - Reduce la Fatiga de usuario.- Agarradera de Transportación - Para su fácil traslado.- Guía de 45° - Permite cortes angulares precisos.- Carbones de fácil Acceso - Provee comodidad a la hora de reemplazarlos.- Traba de eje incorporada - Para un cambio de disco en forma fácil y rápida.- Guarda robusta -Provee mayor seguridad al usuario. - Prensa - Traba rápida y firmemente los materiales al ser cortados, aumentando la productividad.- Velocidad 4000 rpm.- Tamaño de Disco 335 mm (14”).- Traba de Eje Sí.- Peso 16 Kg (35,2 lbs).INCLUYE:- Prensa.- Disco de Corte.- 3 Años de Garantía",
    price: 74850,
    stock: 50,
    initial: 1,
    manufactured: "DeWalt",
    model: "D28730",
    voltage: 220,
    weight: "16",
  },
  {
    id: 4,
    category: "oscilantes",
    name: "Herramienta Oscilante Multiuso Einhell Varrito 18v Multiprop",
    image1: "https://i.imgur.com/vYi6o1B.png",
    image2: "https://i.imgur.com/oQ01G7u.png",
    image3: "https://i.imgur.com/xmIuzt7.png",
    description:
      " La herramienta sin cable multifunción Einhell Varrito supone una ayuda flexible y de calidad para realizar trabajos de desmontaje, renovación o saneamiento. Gracias a su amplio equipamiento, tareas como serrar, pulir o raspar se realizan sin esfuerzo. Como miembro de la familia Power X-Change, ofrece al usuario todos los beneficios de la tecnología de ion de litio de alta calidad de Einhell. La herramienta sin cable multifunción cuenta con una elevada calidad y diseño ergonómico, por lo que su uso en la práctica representa un tremendo alivio.",
    price: 32990,
    stock: 50,
    initial: 1,
    manufactured: "Einhell",
    model: "VARRITO",
    voltage: 220,
    weight: "1,5",
  },

  {
    id: 5,
    category: "oscilantes",
    name: "Multiherramienta Gop 30-28 Bosch",
    image1: "https://i.imgur.com/Olm2CsX.png",
    image2: "https://i.imgur.com/pn6Zgwz.png",
    image3: "https://i.imgur.com/0fhIABM.png",
    description:
      " Herramienta de categoría StarlockPlus para un mayor rendimiento Interfaz magnética para un cambio de herramienta sencillo",
    price: 32990,
    stock: 25,
    initial: 1,
    manufactured: "Bosch",
    model: "Gop 30-28",
    voltage: 220,
    weight: "1,5",
  },

  {
    id: 6,
    category: "oscilantes",
    name: "Multi Herramienta Makita Oscilante Dtm50zx1 18v Litio Bb",
    image1: "https://i.imgur.com/rPcnjrU.png",
    image2: "https://i.imgur.com/viuHt50.png",
    image3: "https://i.imgur.com/vZYbrMo.png",
    description:
      "Posibilidad de cambiar accesorios según las necesidades.Alto rendimiento del trabajo-velocidad 6.000-20.000/min. Sistema de regulación de velocidad.Posibilidad de conectar el aspirador para trabajo limpio y cómodo.12 Niveles de angulo de los accesorios cada 30° de 0° hasta 360° para un campo mas amplio de aplicaciones. Arranque suave.   Utilizando accesorios adecuados es posible realizar muchas tareas como por ejemplo: hacer ranuras en madera, cortar elementos de ceramica, cortar cerca de esquinas y bordes, quitar mortero, silicona, etc.",
    price: 66104,
    stock: 10,
    initial: 1,
    manufactured: "Makitah",
    model: "DTM50",
    voltage: 220,
    weight: "2",
  },

  {
    id: 7,
    category: "termofusoras",
    name: "Termofusora Tawak 800 W + 6 Boq + Tijera + Maletin Agua Gas",
    image1: "https://i.imgur.com/ppHwzw1.png",
    image2: "https://i.imgur.com/QQdXww5.png",
    image3: "https://i.imgur.com/Yll6ggy.png",
    description:
      "MODELO TK 02 -Potencia 800 W -Cantidad de boquillas 6 unidades -Medidas ø 20/25/32/40/50/63 mm (0,78'/ 0,98'/ 1,25'/ 1,57'/ 1,96'/ 2,48')-Alimentación 220 V / 50Hz.-Cuerpo Metalico-Mango recubierto PVC -Temperatura Variable º a 300º C -Luz testigo de temperatura -Incluye Maletín Plástico y Soporte",
    price: 6789,
    stock: 100,
    initial: 1,
    manufactured: "Tawak",
    model: "TK 02",
    voltage: 220,
    weight: "2",
  },
  {
    id: 8,
    category: "termofusoras",
    name: "Termofusora 1500w Uso Profesiona Agua Gas 6 Boquilla Maletin",
    image1: "https://i.imgur.com/ug9t32J.png",
    image2: "https://i.imgur.com/DDA75tx.png",
    image3: "https://i.imgur.com/eJ9u3Cy.png",
    description:
      "* Motor de 1500w ideal para uso profesional  * Sirve para caños de agua y gas  * Por su excelente potencia puede ser utilizada tanto en interiores como exteriores  * Luz testigo de temperatura • Doble led de indicación de temperatura • Alimentación:220 V/ 50Hz  • Temperatura Variable: 0-300 ºC • Diámetro 20 - 63 mm.",
    price: 11267,
    stock: 75,
    initial: 1,
    manufactured: "Omaha",
    model: "TF-1500",
    voltage: 220,
    weight: "2",
  },
  {
    id: 9,
    category: "termofusoras",
    name: "Termofusora Acquasystem 1400w Boq Ø 20 A 63mm Y De 1/2 A 4",
    image1: "https://i.imgur.com/op6Ty8a.png",
    image2: "https://i.imgur.com/rmIYdqr.png",
    image3: "https://i.imgur.com/Zs675AK.png",
    description:
      "SISTEMA ELECTRONICO QUE PERMITE LLEGAR A LA TEMPERATURA OPTIMA PARA LA FUSION SIN FLUCTUACIONES - INCLUYE: TERMOFUSORA 1400 WATTS + 15 BOQUILLAS + SOPORTE en Caja Carton",
    price: 84348,
    stock: 25,
    initial: 1,
    manufactured: "Aqua System",
    model: "08-900111",
    voltage: 220,
    weight: "3,5",
  },
  {
    id: 10,
    category: "perforacion",
    name: "Taladro percutor eléctrico de 13mm Bosch GSB 550 RE 550W con caja de cartón 220V         ",
    image1: "https://i.imgur.com/V4iPiVD.png",
    image2: "https://i.imgur.com/AxPowst.png",
    image3: "https://i.imgur.com/63yODJp.png",
    description:
      "Tecnología de excelencia. Su mandril de 13 mm te permitirá manipular fácilmente la herramienta de manera segura y precisa. Además, su velocidad variable ofrece una gran experiencia de uso, adaptada a tus necesidades y requerimentos.",
    price: 12349,
    stock: 200,
    initial: 1,
    manufactured: "Bosch",
    model: "GSB 550 RE",
    voltage: 220,
    weight: "1,3",
  },
  {
    id: 11,
    category: "perforacion",
    name: "Taladro percutor eléctrico de 13mm DeWalt DWD024 710W + accesorios 220V 50Hz",
    image1: "https://i.imgur.com/dBcP69M.png",
    image2: "https://i.imgur.com/5ZIyZP1.png",
    image3: "https://i.imgur.com/cy7dqri.png",
    description:
      "Su mandril de 13 mm te permitirá manipular fácilmente la herramienta de manera segura y precisa. Además, su velocidad variable ofrece una gran experiencia de uso, adaptada a tus necesidades y requerimentos.",
    price: 20074,
    stock: 75,
    initial: 1,
    manufactured: "DeWalt",
    model: "DWD024",
    voltage: 220,
    weight: "1,8",
  },
  {
    id: 12,
    category: "perforacion",
    name: "Taladro Base Magnetica Bosch 1200w Gbm 50-2 220v Para Metal",
    image1: "https://i.imgur.com/BCqiARh.png",
    image2: "https://i.imgur.com/DNxp2Cg.png",
    image3: "https://i.imgur.com/wNs5WOa.png",
    description:
      "El Taladro sin impacto Bosch GBM 50-2 es la solución ideal para trabajos precisos de perforación en metales. Tiene un potente motor de 1200W para perforaciones más difíciles, tecnología a láser para ayudar en la perforación totalmente centralizada y sistema de protección para el operador contra descargas eléctricas. Su base con alta fuerza magnética ofrece apoyo firme al taladro, sea en la vertical o en la horizontal.",
    price: 675748,
    stock: 15,
    initial: 1,
    manufactured: "Bosch",
    model: "GBM 50-2",
    voltage: 220,
    weight: "14,7",
  },
  {
    id: 13,
    category: "soldadura",
    name: "Soldadora inverter Stanley Sirio 210 50Hz/60Hz 230V",
    image1: "https://i.imgur.com/YTBMfaQ.png",
    image2: "https://i.imgur.com/yjN30a2.png",
    image3: "https://i.imgur.com/AHCowO8.png",
    description:
      "Stanley Sirio 210 es ideal para uso doméstico y profesional. Su calidad brinda una fusión precisa, para que puedas soldar diversos materiales, aplicando calor y proporcionando mayor resistencia. Tecnología eficaz. Al ser de tipo MMA, cuenta con una salida de corriente alterna y es apta para el uso de electrodos especiales y comunes. La principal ventaja es que puede utilizarse en cualquier posición en casi todos los materiales, lo que la convierte en la compañera ideal para soldar uniones que no se pueden colocar en la posición plana.",
    price: 54589,
    stock: 40,
    initial: 1,
    manufactured: "Stanley",
    model: "Sirio 210",
    voltage: 220,
    weight: "3,4",
  },
  {
    id: 14,
    category: "soldadura",
    name: "Soldadora Inverter Duca Mig 350 Amp Trifasica 380v Cable 3 M",
    image1: "https://i.imgur.com/mNUrwUz.png",
    image2: "https://i.imgur.com/E9vKElN.png",
    image3: "https://i.imgur.com/kUooYvU.png",
    description:
      "Soldadora Inverter Duca Mig 350 Amp Trifasica 380v Cable 3 M - Soldadora Inverter Duca MIG SP 350 *Corriente: 380V 50Hz *Corriente De Salida: 50 a 350 A *Para Alambre: De 0.8 a 1.2 Mm *Proteccion: IP21S *Aislacion: F *Dimensiones: 705 X 307 X 500 Mm",
    price: 1034000,
    stock: 4,
    initial: 1,
    manufactured: "Duca",
    model: "69381860",
    voltage: 380,
    weight: "57",
  },
  {
    id: 15,
    category: "fresadoras",
    name: "Fresadora Skil 1831 1100W 220V",
    image1: "https://i.imgur.com/qgql6cI.png",
    image2: "https://i.imgur.com/WX8IoTm.png",
    image3: "https://i.imgur.com/5WdzBBA.png",
    description:
      "Skil 1831 ofrece mayor durabilidad, practicidad y ergonomía al usuario, ya que sus empuñaduras son de goma y encajan perfectamente en la mano. Además, con el preselector de rotaciones es posible elegir cuál es la mejor velocidad para cada tipo de material y acabado. Cuenta con una guía paralela perfecta para seguir tus marcas o trazos al pie de la letra. Las superficies quedarán tan lisas, que no será necesario lijarlas.",
    price: 18998,
    stock: 80,
    initial: 1,
    manufactured: "Skil",
    model: "69381860",
    voltage: 220,
    weight: "2",
  },
  {
    id: 16,
    category: "fresadoras",
    name: "Fresadora Dewalt Dw621 1100w 220v Tupi Velocidad Variable",
    image1: "https://i.imgur.com/EiKGCdD.png",
    image2: "https://i.imgur.com/FQCuQl5.png",
    image3: "https://i.imgur.com/WWgXm5I.png",
    description:
      "sta fresadora será tu herramienta ideal para realizar incisiones precisas en diversos materiales. Además, podrás crear piezas de diseño con distintas formas y tamaños. Para utilizarla, primero, deberás sujetar con firmeza la fresa en la pinza de la máquina y así regular la profundidad máxima del fresado en función del tipo de corte; por último, deberás bloquear la pieza, para asegurar la exactitud. Regulá tus tiempos con sus diferentes velocidades, serás capaz de regular los niveles para lograr la precisión y la potencia necesaria para cada trabajo. Complementos y accesorios. Asimismo, cuenta con un adaptador para extraer el polvo, con el fin de preservar tu salud y el buen estado del equipo.",
    price: 293809,
    stock: 8,
    initial: 1,
    manufactured: "DeWalt",
    model: "DW621",
    voltage: 220,
    weight: "4",
  },
  {
    id: 17,
    category: "otros",
    name: "Hidrolavadora Alta Presion Karcher K5 145 Bar 2100 Watt",
    image1: "https://i.imgur.com/lUOlrkm.png",
    image2: "https://i.imgur.com/0nL5Ofc.png",
    image3: "https://i.imgur.com/tYZ3pVT.png",
    description:
      "Hidrolavadora Karcher K5, equipo ideal para remover la suciedad más difícil. Es un equipo versatil para utilizar en la casa, en el auto, la moto y bicicleta. La hidrolavadora está equipada con un potente motor refrigerado por agua y dispone de una pistola con sistema de acople de acción rápida Quick Connect y una manguera de alta presión de 8 m.También incluye un tubo pulverizador Vario Power (VPS) para un ajuste de la presión cómodo y según las necesidades y para el tratamiento suave de superficies delicadas, así como una boquilla turbo con un potente chorro giratorio contra la suciedad más incrustada. El filtro de agua integrado proporciona protección a la bomba. El paquete se completa con el limpiador universal P&C.Sistema de depósito de detergente incorporado con dosification control incorporado.",
    price: 119389,
    stock: 6,
    initial: 1,
    manufactured: "Kärcher",
    model: "K5",
    voltage: 220,
    weight: "12,8",
  },
  {
    id: 18,
    category: "otros",
    name: "Detector De Materiales Bosch Cables Madera Metales Gms 120",
    image1: "https://i.imgur.com/7oIwHUF.png",
    image2: "https://i.imgur.com/b2R5sEd.png",
    image3: "https://i.imgur.com/7e73yTv.png",
    description:
      "Hidrolavadora Karcher K5, equipo ideal para remover la suciedad más difícil. Es un equipo versatil para utilizar en la casa, en el auto, la moto y bicicleta. La hidrolavadora está equipada con un potente motor refrigerado por agua y dispone de una pistola con sistema de acople de acción rápida Quick Connect y una manguera de alta presión de 8 m.También incluye un tubo pulverizador Vario Power (VPS) para un ajuste de la presión cómodo y según las necesidades y para el tratamiento suave de superficies delicadas, así como una boquilla turbo con un potente chorro giratorio contra la suciedad más incrustada. El filtro de agua integrado proporciona protección a la bomba. El paquete se completa con el limpiador universal P&C.Sistema de depósito de detergente incorporado con dosification control incorporado.",
    price: 20699,
    stock: 80,
    initial: 1,
    manufactured: "Bosch",
    model: "GMS 120",
    voltage: 220,
    weight: "1,1",
  },
];
